WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080
BOTTOM_BAR_HEIGHT = 100

GRID_ROWS = 50
GRID_COLS = 50
CELL_SIZE = (WINDOW_HEIGHT - BOTTOM_BAR_HEIGHT) // GRID_ROWS 

GRID_WIDTH = GRID_COLS * CELL_SIZE 
GRID_HEIGHT = GRID_ROWS * CELL_SIZE  
GRID_ORIGIN_X = (WINDOW_WIDTH - GRID_WIDTH) 
GRID_ORIGIN_Y = (WINDOW_HEIGHT - BOTTOM_BAR_HEIGHT - GRID_HEIGHT)

COLOR_EMPTY = (200, 200, 200) 
COLOR_TYPE1 = (0, 0, 255)
COLOR_TYPE2 = (255, 0, 0) 
COLOR_GRID_LINE = (150, 150, 150)

GRAPH_AREA_X = GRID_ORIGIN_X + GRID_WIDTH + 20
GRAPH_AREA_Y = GRID_ORIGIN_Y
GRAPH_AREA_WIDTH = WINDOW_WIDTH - GRAPH_AREA_X - 20
GRAPH_AREA_HEIGHT = GRID_HEIGHT

FPS = 30
